version: '3'
services:
  db:
    image: brancosmith/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - C:\Concessionaria\bases\mysql:/var/lib/mysql
  web:
    image: brancosmith/ubuntu
    ports:
      - "80:80"
    volumes:
      - C:\Concessionaria:/var/www/html
    links:
     - db

     